"""empty message

Revision ID: 27a01b105bf7
Revises: ab18df04cf36
Create Date: 2025-03-16 12:54:41.087827

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "27a01b105bf7"
down_revision = "ab18df04cf36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("my_service", schema=None) as batch_op:
        batch_op.drop_column("encrypted_password")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("my_service", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "encrypted_password", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            )
        )

    # ### end Alembic commands ###
