"""empty message

Revision ID: 3a1018bb4a59
Revises: cf744a334061
Create Date: 2025-03-13 09:14:47.465739

"""

# revision identifiers, used by Alembic.
revision = "3a1018bb4a59"
down_revision = "cf744a334061"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


# ### end Alembic commands ###


def downgrade():
    pass

    # ### end Alembic commands ###
