"""empty message

Revision ID: 83291c1e9b53
Revises: c52261e42b5b
Create Date: 2025-03-05 10:21:50.966246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83291c1e9b53'
down_revision = 'c52261e42b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_service', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
