"""empty message

Revision ID: 8537a57f7de7
Revises: 83291c1e9b53
Create Date: 2025-03-05 10:31:28.312363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8537a57f7de7'
down_revision = '83291c1e9b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        # Ajouter la nouvelle colonne pour la clé étrangère
        batch_op.add_column(
            sa.Column('my_service_id', sa.Integer(), nullable=True))

        # Si la contrainte fk_support_ticket_my_service n'existe pas, créez-la
        batch_op.create_foreign_key('fk_support_ticket_my_service', 'my_service', [
                                    'my_service_id'], ['id'])

        # Supprimer la colonne cart_line_id si nécessaire
        batch_op.drop_column('cart_line_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        # Si vous avez besoin de restaurer cart_line_id dans la rétrogradation
        batch_op.add_column(
            sa.Column('cart_line_id', sa.INTEGER(), nullable=True))

        # Restaurer la contrainte FK d'origine sur cart_line si elle avait été supprimée
        batch_op.create_foreign_key('fk_support_ticket_cart_line', 'cart_line', [
                                    'cart_line_id'], ['id'])

        # Supprimer la colonne my_service_id dans le cas de la rétrogradation
        batch_op.drop_column('my_service_id')

    # ### end Alembic commands ###
