"""empty message

Revision ID: 95fc98f22bfe
Revises: df0a140c3fda
Create Date: 2025-03-12 13:00:27.629090

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "95fc98f22bfe"
down_revision = "df0a140c3fda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("my_service", schema=None) as batch_op:
        batch_op.add_column(sa.Column("encrypted_password", sa.String(length=255), nullable=False))
        batch_op.drop_column("password")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("my_service", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("encrypted_password")

    # ### end Alembic commands ###
