"""empty message

Revision ID: ab18df04cf36
Revises: 51e7ea852bd0
Create Date: 2025-03-16 12:39:57.443466

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab18df04cf36"
down_revision = "51e7ea852bd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("my_service", schema=None) as batch_op:
        batch_op.add_column(sa.Column("api_key", sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("my_service", schema=None) as batch_op:
        batch_op.drop_column("api_key")

    # ### end Alembic commands ###
