"""empty message

Revision ID: cf744a334061
Revises: 95fc98f22bfe
Create Date: 2025-03-12 13:07:52.346687

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cf744a334061"
down_revision = "95fc98f22bfe"
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table("my_service", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_encrypted", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("my_service", schema=None) as batch_op:
        batch_op.drop_column("is_encrypted")

    # ### end Alembic commands ###
