"""empty message

Revision ID: df0a140c3fda
Revises: 4945e4ad9864
Create Date: 2025-03-12 12:59:23.835961

"""

# revision identifiers, used by Alembic.
revision = "df0a140c3fda"
down_revision = "4945e4ad9864"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    pass
    # ### end Alembic commands ###
